### PR TITLE
handle energy windows and various other small improvements

### PR DESCRIPTION
**Pull request by KrisThielemans**

### CODE REVIEW

**Comment by KrisThielemans** [comment]
@danieldeidda note that I've changed the calling sequence. It now writes one file per energy windows.

**Comment by danieldeidda** [comment]
> @danieldeidda note that I've changed the calling sequence. It now writes one file per energy windows.

is it normal that I get 120 modified files?

**Review by danieldeidda — COMMENTED** [review]
nice! have you run this with multiple energy data?

**Comment by KrisThielemans** [comment]
> > @danieldeidda note that I've changed the calling sequence. It now writes one file per energy windows.
> 
> is it normal that I get 120 modified files?

oops. no, I just changed 2 files. Maybe because I merged with master or something. I'm a bit confused about the history now. Maybe we can check later in our meeting.

**Comment by KrisThielemans** [comment]
abandoned due to inadvertent rebase. replaced by #2

**Pull request closed without merging**
